In [1]:
import numpy as np
import pandas as pd

In [2]:
corpus = "bgsner"
bgsner_metrics_albert = pd.read_csv("bgsner/albert-base-v2_overall_metrics.csv")
name = "albert"
bgsner_metrics_albert_selected = bgsner_metrics_albert[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

bgsner_metrics_bert = pd.read_csv(
    "bgsner/bert-base-cased_overall_metrics.csv"
)
name = "bert"
bgsner_metrics_bert_selected = bgsner_metrics_bert[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

bgsner_metrics_roberta = pd.read_csv(
    "bgsner/xlm-roberta-base_overall_metrics.csv"
)
name = "roberta"
bgsner_metrics_roberta_selected = bgsner_metrics_roberta[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

merged_bgsner = bgsner_metrics_bert_selected.merge(
    bgsner_metrics_albert_selected, on="split", how="outer"
).merge(bgsner_metrics_roberta_selected, on="split", how="outer")

In [3]:
merged_bgsner

,split,overall_accuracy_bert_bgsner,f1_macro_bert_bgsner,overall_accuracy_albert_bgsner,f1_macro_albert_bgsner,overall_accuracy_roberta_bgsner,f1_macro_roberta_bgsner
0,advs,0.996951,0.985734,0.996951,0.985734,0.996951,0.985734
1,heur_len,0.995493,0.807781,0.995493,0.807781,0.995493,0.807781
2,heur_rare,0.995367,0.902477,0.995367,0.902477,0.995367,0.902477
3,loc,0.993051,0.891938,0.993051,0.891938,0.993051,0.891938
4,reverse,0.991870,0.858211,0.991870,0.858211,0.991870,0.858211
5,semantic,0.996079,0.980705,0.996144,0.983486,0.996079,0.980705
6,std,0.993445,0.974101,0.993445,0.974101,0.993445,0.974101
7,std,0.993445,0.974101,0.994401,0.966686,0.993445,0.974101

In [4]:
geocorpus_metrics_albert = pd.read_csv("geocorpus/albertina-base_overall_metrics.csv")

In [5]:
geocorpus_metrics_albert

,split,eval_loss,overall_precision,overall_recall,overall_f1,overall_accuracy,f1_micro,f1_macro,f1_weighted,runtime_s,samples_per_sec,steps_per_sec,epoch
0,loc,0.053772,0.850193,0.882212,0.865906,0.988793,0.988793,0.658709,0.988479,6.4597,163.164,10.217,5.0
1,reverse,0.473298,0.786553,0.625350,0.696749,0.942391,0.942391,0.392629,0.928779,13.0759,80.606,5.047,5.0
2,semantic,0.046634,0.840456,0.909792,0.873750,0.989894,0.989894,0.666881,0.989722,6.8975,156.724,9.859,5.0
3,heur_len,0.065568,0.844094,0.893333,0.868016,0.985897,0.985897,0.679663,0.985649,8.6430,121.948,7.636,5.0
4,heur_rare,0.073530,0.815592,0.889373,0.850886,0.984488,0.984488,0.652366,0.984317,9.7123,108.522,6.796,5.0
5,advs,0.161043,0.785914,0.794820,0.790342,0.972233,0.972233,0.629255,0.969249,10.8164,97.444,6.102,5.0

In [6]:
corpus = 'geocorpus'
geocorpus_metrics_albert = pd.read_csv("geocorpus/albertina-base_overall_metrics.csv")
name = "albert"
geocorpus_metrics_albert_selected = geocorpus_metrics_albert[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

geocorpus_metrics_bert = pd.read_csv(
    "geocorpus/bert-base-portuguese-cased_overall_metrics.csv"
)
name = "bert"
geocorpus_metrics_bert_selected = geocorpus_metrics_bert[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

geocorpus_metrics_roberta = pd.read_csv(
    "geocorpus/xlm-roberta-base_overall_metrics.csv"
)
name = "roberta"
geocorpus_metrics_roberta_selected = geocorpus_metrics_roberta[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

In [7]:
merged_geocorpus = geocorpus_metrics_bert_selected.merge(
    geocorpus_metrics_albert_selected, on="split", how="outer"
).merge(geocorpus_metrics_roberta_selected, on="split", how="outer")

In [8]:
merged = merged_bgsner.merge(
    merged_geocorpus, on="split", how="outer")

In [9]:
merged

,split,overall_accuracy_bert_bgsner,f1_macro_bert_bgsner,overall_accuracy_albert_bgsner,f1_macro_albert_bgsner,overall_accuracy_roberta_bgsner,f1_macro_roberta_bgsner,overall_accuracy_bert_geocorpus,f1_macro_bert_geocorpus,overall_accuracy_albert_geocorpus,f1_macro_albert_geocorpus,overall_accuracy_roberta_geocorpus,f1_macro_roberta_geocorpus
0,advs,0.996951,0.985734,0.996951,0.985734,0.996951,0.985734,0.972233,0.629255,0.972233,0.629255,0.972562,0.606667
1,heur_len,0.995493,0.807781,0.995493,0.807781,0.995493,0.807781,0.985897,0.679663,0.985897,0.679663,0.986076,0.701017
2,heur_rare,0.995367,0.902477,0.995367,0.902477,0.995367,0.902477,0.984488,0.652366,0.984488,0.652366,0.984677,0.663345
3,loc,0.993051,0.891938,0.993051,0.891938,0.993051,0.891938,0.988793,0.658709,0.988793,0.658709,0.987802,0.629480
4,reverse,0.991870,0.858211,0.991870,0.858211,0.991870,0.858211,0.942391,0.392629,0.942391,0.392629,0.940798,0.404204
5,semantic,0.996079,0.980705,0.996144,0.983486,0.996079,0.980705,0.989894,0.666881,0.989894,0.666881,0.990322,0.667235
6,std,0.993445,0.974101,0.993445,0.974101,0.993445,0.974101,NaN,NaN,NaN,NaN,NaN,NaN
7,std,0.993445,0.974101,0.994401,0.966686,0.993445,0.974101,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
merged.columns

Index(['split', 'overall_accuracy_bert_bgsner', 'f1_macro_bert_bgsner',
       'overall_accuracy_albert_bgsner', 'f1_macro_albert_bgsner',
       'overall_accuracy_roberta_bgsner', 'f1_macro_roberta_bgsner',
       'overall_accuracy_bert_geocorpus', 'f1_macro_bert_geocorpus',
       'overall_accuracy_albert_geocorpus', 'f1_macro_albert_geocorpus',
       'overall_accuracy_roberta_geocorpus', 'f1_macro_roberta_geocorpus'],
      dtype='object')

In [11]:
split_order = ["std", "heur_len", "heur_rare", "advs", "loc", "semantic", "reverse"]

merged["split"] = merged["split"].astype(str).str.strip()

merged["split"] = pd.Categorical(merged["split"], categories=split_order, ordered=True)
merged = merged.sort_values("split", kind="stable").reset_index(
    drop=True
)

In [12]:
accuracy_df = merged[["split"] + [c for c in merged.columns if "accuracy" in c]]

In [13]:
accuracy_df

,split,overall_accuracy_bert_bgsner,overall_accuracy_albert_bgsner,overall_accuracy_roberta_bgsner,overall_accuracy_bert_geocorpus,overall_accuracy_albert_geocorpus,overall_accuracy_roberta_geocorpus
0,std,0.993445,0.993445,0.993445,NaN,NaN,NaN
1,std,0.993445,0.994401,0.993445,NaN,NaN,NaN
2,heur_len,0.995493,0.995493,0.995493,0.985897,0.985897,0.986076
3,heur_rare,0.995367,0.995367,0.995367,0.984488,0.984488,0.984677
4,advs,0.996951,0.996951,0.996951,0.972233,0.972233,0.972562
5,loc,0.993051,0.993051,0.993051,0.988793,0.988793,0.987802
6,semantic,0.996079,0.996144,0.996079,0.989894,0.989894,0.990322
7,reverse,0.991870,0.991870,0.991870,0.942391,0.942391,0.940798

In [14]:
f1_df = merged[["split"] + [c for c in merged.columns if "f1_macro" in c]]

In [15]:
f1_df

,split,f1_macro_bert_bgsner,f1_macro_albert_bgsner,f1_macro_roberta_bgsner,f1_macro_bert_geocorpus,f1_macro_albert_geocorpus,f1_macro_roberta_geocorpus
0,std,0.974101,0.974101,0.974101,NaN,NaN,NaN
1,std,0.974101,0.966686,0.974101,NaN,NaN,NaN
2,heur_len,0.807781,0.807781,0.807781,0.679663,0.679663,0.701017
3,heur_rare,0.902477,0.902477,0.902477,0.652366,0.652366,0.663345
4,advs,0.985734,0.985734,0.985734,0.629255,0.629255,0.606667
5,loc,0.891938,0.891938,0.891938,0.658709,0.658709,0.629480
6,semantic,0.980705,0.983486,0.980705,0.666881,0.666881,0.667235
7,reverse,0.858211,0.858211,0.858211,0.392629,0.392629,0.404204