In [1]:
import numpy as np
import pandas as pd

In [2]:
corpus = "ener"
ener_metrics_albert = pd.read_csv("ener/albert-base-v2_overall_metrics.csv")
name = "albert"
ener_metrics_albert_selected = ener_metrics_albert[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

ener_metrics_bert = pd.read_csv(
    "ener/bert-base-cased_overall_metrics.csv"
)
name = "bert"
ener_metrics_bert_selected = ener_metrics_bert[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

ener_metrics_roberta = pd.read_csv(
    "ener/xlm-roberta-base_overall_metrics.csv"
)
name = "roberta"
ener_metrics_roberta_selected = ener_metrics_roberta[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

merged_ener = ener_metrics_bert_selected.merge(
    ener_metrics_albert_selected, on="split", how="outer"
).merge(ener_metrics_roberta_selected, on="split", how="outer")

In [3]:
merged_ener

,split,overall_accuracy_bert_ener,f1_macro_bert_ener,overall_accuracy_albert_ener,f1_macro_albert_ener,overall_accuracy_roberta_ener,f1_macro_roberta_ener
0,advs,0.995116,0.709947,0.995116,0.709947,0.995116,0.709947
1,heur_len,0.995329,0.720923,0.995341,0.721066,0.995329,0.720923
2,heur_rare,0.986892,0.514340,0.986892,0.514340,0.986881,0.514258
3,loc,0.984994,0.551618,0.984994,0.551618,0.984994,0.551618
4,reverse,0.937248,0.329959,0.937248,0.329959,0.937248,0.329959
5,semantic,0.986599,0.733467,0.986599,0.733467,0.986599,0.733467

In [4]:
corpus = 'lener'
lener_metrics_albert = pd.read_csv("lener/albertina-base_overall_metrics.csv")
name = "albert"
lener_metrics_albert_selected = lener_metrics_albert[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

lener_metrics_bert = pd.read_csv(
    "lener/bert-base-portuguese-cased_overall_metrics.csv"
)
name = "bert"
lener_metrics_bert_selected = lener_metrics_bert[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

lener_metrics_roberta = pd.read_csv(
    "lener/xlm-roberta-base_overall_metrics.csv"
)
name = "roberta"
lener_metrics_roberta_selected = lener_metrics_roberta[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

In [5]:
merged_lener = lener_metrics_bert_selected.merge(
    lener_metrics_albert_selected, on="split", how="outer"
).merge(lener_metrics_roberta_selected, on="split", how="outer")

In [6]:
merged = merged_lener.merge(merged_ener, on="split", how="outer")

In [7]:
merged

,split,overall_accuracy_bert_lener,f1_macro_bert_lener,overall_accuracy_albert_lener,f1_macro_albert_lener,overall_accuracy_roberta_lener,f1_macro_roberta_lener,overall_accuracy_bert_ener,f1_macro_bert_ener,overall_accuracy_albert_ener,f1_macro_albert_ener,overall_accuracy_roberta_ener,f1_macro_roberta_ener
0,advs,0.985758,0.919110,0.985758,0.919110,0.985758,0.919110,0.995116,0.709947,0.995116,0.709947,0.995116,0.709947
1,heur_len,0.989272,0.943389,0.989272,0.943389,0.989272,0.943389,0.995329,0.720923,0.995341,0.721066,0.995329,0.720923
2,heur_rare,0.986071,0.929803,0.986071,0.929803,0.986071,0.929803,0.986892,0.514340,0.986892,0.514340,0.986881,0.514258
3,loc,0.987900,0.874908,0.987900,0.874908,0.987900,0.874908,0.984994,0.551618,0.984994,0.551618,0.984994,0.551618
4,reverse,0.905898,0.721392,0.905898,0.721392,0.905898,0.721392,0.937248,0.329959,0.937248,0.329959,0.937248,0.329959
5,semantic,0.978174,0.867601,0.978174,0.867601,0.978174,0.867601,0.986599,0.733467,0.986599,0.733467,0.986599,0.733467
6,std,0.984291,0.880277,0.984249,0.880182,0.984249,0.880182,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
merged.columns

Index(['split', 'overall_accuracy_bert_lener', 'f1_macro_bert_lener',
       'overall_accuracy_albert_lener', 'f1_macro_albert_lener',
       'overall_accuracy_roberta_lener', 'f1_macro_roberta_lener',
       'overall_accuracy_bert_ener', 'f1_macro_bert_ener',
       'overall_accuracy_albert_ener', 'f1_macro_albert_ener',
       'overall_accuracy_roberta_ener', 'f1_macro_roberta_ener'],
      dtype='object')

In [9]:
split_order = ["std", "heur_len", "heur_rare", "advs", "loc", "semantic", "reverse"]

merged["split"] = merged["split"].astype(str).str.strip()

merged["split"] = pd.Categorical(merged["split"], categories=split_order, ordered=True)
merged = merged.sort_values("split", kind="stable").reset_index(
    drop=True
)

In [10]:
accuracy_df = merged[["split"] + [c for c in merged.columns if "accuracy" in c]]

In [11]:
accuracy_df

,split,overall_accuracy_bert_lener,overall_accuracy_albert_lener,overall_accuracy_roberta_lener,overall_accuracy_bert_ener,overall_accuracy_albert_ener,overall_accuracy_roberta_ener
0,std,0.984291,0.984249,0.984249,NaN,NaN,NaN
1,heur_len,0.989272,0.989272,0.989272,0.995329,0.995341,0.995329
2,heur_rare,0.986071,0.986071,0.986071,0.986892,0.986892,0.986881
3,advs,0.985758,0.985758,0.985758,0.995116,0.995116,0.995116
4,loc,0.987900,0.987900,0.987900,0.984994,0.984994,0.984994
5,semantic,0.978174,0.978174,0.978174,0.986599,0.986599,0.986599
6,reverse,0.905898,0.905898,0.905898,0.937248,0.937248,0.937248

In [12]:
f1_df = merged[["split"] + [c for c in merged.columns if "f1_macro" in c]]

In [13]:
f1_df

,split,f1_macro_bert_lener,f1_macro_albert_lener,f1_macro_roberta_lener,f1_macro_bert_ener,f1_macro_albert_ener,f1_macro_roberta_ener
0,std,0.880277,0.880182,0.880182,NaN,NaN,NaN
1,heur_len,0.943389,0.943389,0.943389,0.720923,0.721066,0.720923
2,heur_rare,0.929803,0.929803,0.929803,0.514340,0.514340,0.514258
3,advs,0.919110,0.919110,0.919110,0.709947,0.709947,0.709947
4,loc,0.874908,0.874908,0.874908,0.551618,0.551618,0.551618
5,semantic,0.867601,0.867601,0.867601,0.733467,0.733467,0.733467
6,reverse,0.721392,0.721392,0.721392,0.329959,0.329959,0.329959