In [1]:
import numpy as np
import pandas as pd

In [2]:
corpus = "cleanconll"
cleanconll_metrics_albert = pd.read_csv("cleanconll/albert-base-v2_overall_metrics.csv")
name = "albert"
cleanconll_metrics_albert_selected = cleanconll_metrics_albert[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

cleanconll_metrics_bert = pd.read_csv(
    "cleanconll/bert-base-cased_overall_metrics.csv"
)
name = "bert"
cleanconll_metrics_bert_selected = cleanconll_metrics_bert[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

cleanconll_metrics_roberta = pd.read_csv(
    "cleanconll/xlm-roberta-base_overall_metrics.csv"
)
name = "roberta"
cleanconll_metrics_roberta_selected = cleanconll_metrics_roberta[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

merged_cleanconll = cleanconll_metrics_bert_selected.merge(
    cleanconll_metrics_albert_selected, on="split", how="outer"
).merge(cleanconll_metrics_roberta_selected, on="split", how="outer")

In [3]:
merged_cleanconll

,split,overall_accuracy_bert_cleanconll,f1_macro_bert_cleanconll,overall_accuracy_albert_cleanconll,f1_macro_albert_cleanconll,overall_accuracy_roberta_cleanconll,f1_macro_roberta_cleanconll
0,advs,0.990551,0.943745,0.990551,0.943745,0.990551,0.943745
1,heur_len,0.993079,0.963338,0.993079,0.963338,0.993079,0.963338
2,heur_rare,0.990838,0.947297,0.990838,0.947297,0.990838,0.947297
3,loc,0.991209,0.935903,0.991209,0.935903,0.991209,0.935903
4,reverse,0.974794,0.898363,0.974794,0.898363,0.974794,0.898363
5,semantic,0.987896,0.958327,0.987896,0.958327,0.987896,0.958327
6,std,0.985098,0.925987,0.985120,0.926674,0.985120,0.926674

In [4]:
corpus = 'cachaca'
cachaca_metrics_albert = pd.read_csv("cachaca/albertina-base_overall_metrics.csv")
name = "albert"
cachaca_metrics_albert_selected = cachaca_metrics_albert[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

cachaca_metrics_bert = pd.read_csv(
    "cachaca/bert-base-portuguese-cased_overall_metrics.csv"
)
name = "bert"
cachaca_metrics_bert_selected = cachaca_metrics_bert[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

cachaca_metrics_roberta = pd.read_csv(
    "cachaca/xlm-roberta-base_overall_metrics.csv"
)
name = "roberta"
cachaca_metrics_roberta_selected = cachaca_metrics_roberta[
    ["split", "overall_accuracy", "f1_macro"]
].rename(
    columns={
        "overall_accuracy": f"overall_accuracy_{name}_{corpus}",
        "f1_macro": f"f1_macro_{name}_{corpus}",
    }
)

merged_cachaca = cachaca_metrics_bert_selected.merge(
    cachaca_metrics_albert_selected, on="split", how="outer"
).merge(cachaca_metrics_roberta_selected, on="split", how="outer")

In [5]:
merged = merged_cleanconll.merge(merged_cachaca, on="split", how="outer")

In [6]:
merged

,split,overall_accuracy_bert_cleanconll,f1_macro_bert_cleanconll,overall_accuracy_albert_cleanconll,f1_macro_albert_cleanconll,overall_accuracy_roberta_cleanconll,f1_macro_roberta_cleanconll,overall_accuracy_bert_cachaca,f1_macro_bert_cachaca,overall_accuracy_albert_cachaca,f1_macro_albert_cachaca,overall_accuracy_roberta_cachaca,f1_macro_roberta_cachaca
0,advs,0.990551,0.943745,0.990551,0.943745,0.990551,0.943745,0.975360,0.877984,0.975360,0.877984,0.975360,0.877984
1,heur_len,0.993079,0.963338,0.993079,0.963338,0.993079,0.963338,0.984219,0.925736,0.984219,0.925736,0.984219,0.925736
2,heur_rare,0.990838,0.947297,0.990838,0.947297,0.990838,0.947297,0.966171,0.845600,0.966171,0.845600,0.966171,0.845600
3,loc,0.991209,0.935903,0.991209,0.935903,0.991209,0.935903,0.957924,0.770105,0.957924,0.770105,0.957924,0.770105
4,reverse,0.974794,0.898363,0.974794,0.898363,0.974794,0.898363,0.902546,0.620090,0.902546,0.620090,0.902546,0.620090
5,semantic,0.987896,0.958327,0.987896,0.958327,0.987896,0.958327,0.772513,0.642346,0.772513,0.642346,0.772513,0.642346
6,std,0.985098,0.925987,0.985120,0.926674,0.985120,0.926674,0.986003,0.933000,0.986003,0.933000,0.986003,0.933000

In [7]:
merged.columns

Index(['split', 'overall_accuracy_bert_cleanconll', 'f1_macro_bert_cleanconll',
       'overall_accuracy_albert_cleanconll', 'f1_macro_albert_cleanconll',
       'overall_accuracy_roberta_cleanconll', 'f1_macro_roberta_cleanconll',
       'overall_accuracy_bert_cachaca', 'f1_macro_bert_cachaca',
       'overall_accuracy_albert_cachaca', 'f1_macro_albert_cachaca',
       'overall_accuracy_roberta_cachaca', 'f1_macro_roberta_cachaca'],
      dtype='object')

In [8]:
split_order = ["std", "heur_len", "heur_rare", "advs", "loc", "semantic", "reverse"]

merged["split"] = merged["split"].astype(str).str.strip()

merged["split"] = pd.Categorical(merged["split"], categories=split_order, ordered=True)
merged = merged.sort_values("split", kind="stable").reset_index(
    drop=True
)

In [9]:
accuracy_df = merged[["split"] + [c for c in merged.columns if "accuracy" in c]]

In [10]:
accuracy_df

,split,overall_accuracy_bert_cleanconll,overall_accuracy_albert_cleanconll,overall_accuracy_roberta_cleanconll,overall_accuracy_bert_cachaca,overall_accuracy_albert_cachaca,overall_accuracy_roberta_cachaca
0,std,0.985098,0.985120,0.985120,0.986003,0.986003,0.986003
1,heur_len,0.993079,0.993079,0.993079,0.984219,0.984219,0.984219
2,heur_rare,0.990838,0.990838,0.990838,0.966171,0.966171,0.966171
3,advs,0.990551,0.990551,0.990551,0.975360,0.975360,0.975360
4,loc,0.991209,0.991209,0.991209,0.957924,0.957924,0.957924
5,semantic,0.987896,0.987896,0.987896,0.772513,0.772513,0.772513
6,reverse,0.974794,0.974794,0.974794,0.902546,0.902546,0.902546

In [11]:
f1_df = merged[["split"] + [c for c in merged.columns if "f1_macro" in c]]

In [12]:
f1_df

,split,f1_macro_bert_cleanconll,f1_macro_albert_cleanconll,f1_macro_roberta_cleanconll,f1_macro_bert_cachaca,f1_macro_albert_cachaca,f1_macro_roberta_cachaca
0,std,0.925987,0.926674,0.926674,0.933000,0.933000,0.933000
1,heur_len,0.963338,0.963338,0.963338,0.925736,0.925736,0.925736
2,heur_rare,0.947297,0.947297,0.947297,0.845600,0.845600,0.845600
3,advs,0.943745,0.943745,0.943745,0.877984,0.877984,0.877984
4,loc,0.935903,0.935903,0.935903,0.770105,0.770105,0.770105
5,semantic,0.958327,0.958327,0.958327,0.642346,0.642346,0.642346
6,reverse,0.898363,0.898363,0.898363,0.620090,0.620090,0.620090